### ISSUE TITLE
socialite doesnt work in your project

### ISSUE THREAD

**Issue by filipve** [evercode1/laraboot#1]
Hi,

I bought your ebook course for laravel 5.1.

Now, i am trying to do what you did with socialite, but when I implemented them all, it says always: Method [socialUserHasNo] does not exist. The AuthController cant seem to find this method that is implemented in the ManagesSocial.php trait file in http/AuthTraits folder.

All the rest works, but this doesnt. What could be wrong?

**Comment by filipve** [comment]
it is fixed by myself. forgot to add ManagesSocial in use in the class AuthController on the first line.

Thanks for the awesome tutorial.

Can i suggest to change your sweetalert from socieboy to infinitety maker because socieboy's package didn't work for me. Same for gravatar in your tutorial doesnt work apparently.

**Comment by evercode1** [comment]
Hi.  Glad you got it working.  At the moment, it doesn't look like I will be revising the book.  Thanks again for the positive feedback.
Bill.

**Comment by filipve** [comment]
Ah, I wanted to ask if it would be possible to write a tutorial somehow on how to send emails through a contact form with a controller with laravel 5.1?

**Comment by evercode1** [comment]
I'm not currently writing tutorials.  You should check out laracasts for that info.
Bill. Bill Keck
