### ISSUE TITLE
TokenMismatchException in VerifyCsrfToken.php line 67

### ISSUE THREAD

**Issue by ckwong** [evercode1/laraboot#2]
When I save in register form (laraboot/public/register)
found shown above captioned error

**Comment by evercode1** [comment]
Hi.  Are you including the following in the registration form:
{!! csrf_field() !!}

Also, if you use the back button while trying to register, you can get a token mismatch. 
I recently updated the book.  Which version of laravel do you have installed and did you start from the beginning?
The book is now using 5.2.27.  You can check the version by running from the command line:
php artisan --version
Bill. 
Bill Keck

**Comment by dadaycm** [comment]
Same problem happened here and I fixed it using the following way:
1, Use command "`_laravel new_`" to build a new laravel5 project,
2, Use compare tool such as **_beyond compare_** to sync most of the files from the package downloaded here to the new project just generated. Of course,  configure files keeps unchanged (using auto-generated). 
3, Run "`_composer install/update_`"
4, migrate
5, Open it from browser, it works!

Hope this helps.

**Comment by evercode1** [comment]
You have to also make sure that your domain key in config/session.php is set properly.
