### ISSUE TITLE
Facebook loginning reports that "The parameter app_id is required"

### ISSUE THREAD

**Issue by dadaycm** [evercode1/laraboot#3]
When the facebook login is triggered, error is shown as "The parameter app_id is required"

the url has been redirected to the following:
https://www.facebook.com/v2.5/dialog/oauth?scope=email&response_type=code&state=...

Ubuntu 14 is used here.
I wonder if there is further configuration needs to do.

**Comment by evercode1** [comment]
Did you set up your .env file with your facebook settings?

**Comment by dadaycm** [comment]
from p266, it is said that the codes below should be set in **_`.env`_** file:
```
_FACEBOOK_ID=your-actual-id
FACEBOOK_SECRET=your-actual-secret
FACEBOOK_URL=http://www.laraboot.com/auth/facebook/callback
_
```but, how to set the value for them? No more hints could be found. I tried to use my facebook ID ( registed email) /password to fill in the first two fields but failed and the same error reported. 
Bill, could you please explain it in more detail? Thanks!

**Comment by evercode1** [comment]
You have to create an app on facebook, which will give you app Id and secret, which you can use to populate your values.  I covered this in detail in the book.  Go to:

https://developers.facebook.com/

Then follow the steps from the book.  Don't forget to set your callback url as instructed.  Also, you need to use your own domain, you can't create an app for laraboot.com, it's already taken.  Don't forget to update config/session.php with the domain key that you are going to use or you will have problems.

**Comment by evercode1** [comment]
closed
